services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=user-microservice-db
    container_name: postgres-container
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - user-api-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-microservice-container
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=123456
      - DB_NAME=user-microservice-db
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - user-api-network

networks:
  user-api-network: 
    driver: bridge
