apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice-deployment
spec:
  template:
    metadata:
      name: user-microservice
      labels: 
        app: user-microservice
    spec:
      containers:
        - name: user-microservice-container
          image: $ECR_REPOSITORY
          resources:
            limits:
              cpu: 1000m
              memory: 2000Mi
            requests:
              cpu: 1000m
              memory: 2000Mi
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: secrets-user-microservice
          livenessProbe:
            httpGet:
              path: /liveness
              port: 80
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: user-microservice        